repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
      - id: isort
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
      - id: black
        args: [--target-version, py39]
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
      - id: flake8
        additional_dependencies:
            [
                flake8-bugbear==20.11.1,
                flake8-builtins==1.5.3,
            ]
- repo: local
  hooks:
    - id: unittest
      name: Run Python Tests
      entry: python -m unittest
      language: python
      types: [ python ]
      pass_filenames: false
      verbose: true
      additional_dependencies: ["django>=3.0"]
